services:
  djangoapp:
    container_name: django_project
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./django_project:/django_project
      - ./django_project/static:/data/web/static/
      - ./django_project/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env