# Generated by Django 5.0.9 on 2024-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('carboidratos_totais_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carboidratos_disponiveis_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carboidratos_totais_200ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carboidratos_disponiveis_200ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
    ]
