# Generated by Django 5.0.6 on 2024-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbmonitor", "0002_alimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="nome",
            field=models.CharField(max_length=500),
        ),
    ]
