# Generated by Django 5.0.6 on 2024-10-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbmonitor", "0003_alter_alimento_nome"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alimento",
            table="alimentos",
        ),
    ]
